spring:
  application:
    name: language-learning-api
  datasource:
    url: ${DB_CONNECT_URL:jdbc:postgresql://localhost:5432/language_learning}
    username: ${DB_USERNAME:hieptran}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379

groq:
  api:
    key: ${GROQ_API_KEY:}
    url: https://api.groq.com/openai/v1/chat/completions
    model: openai/gpt-oss-safeguard-20b
    max-tokens: 4000
    temperature: 0.3
    # Word translation specific config
    word-translation:
      model: llama-3.1-8b-instant
      max-tokens: 1000
      temperature: 0.3

server:
  port: 8081
