spring:
  application:
    name: language-learning-api
  datasource:
    url: jdbc:postgresql://localhost:5432/language_learning
    username: ${DB_USERNAME:hieptran}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379

groq:
  api:
    key: ${GROQ_API_KEY:}
    url: https://api.groq.com/openai/v1/chat/completions
    model: llama-3.1-8b-instant
    max-tokens: 2000
    temperature: 0.3

server:
  port: 8081
